# Generated by Django 3.1.2 on 2022-05-27 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0002_auto_20220523_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifterapplicant',
            name='applicant_num',
            field=models.CharField(max_length=10, null=True, verbose_name='applicant_num'),
        ),
        migrations.AddField(
            model_name='transfereeapplicant',
            name='applicant_num',
            field=models.CharField(max_length=10, null=True, verbose_name='applicant_num'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 13, 49, 14, 11679, tzinfo=utc)),
        ),
    ]
